version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 3  # Scale app instances dynamically
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 5s
      retries: 5
      timeout: 3s

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - app

networks:
  app_network:
    driver: bridge
